import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CalendarCheck, Sparkles, Trash2 } from "lucide-react";
import { PageHeader, Panel, OutputState } from "@/components/AppShell";
import { useAI } from "@/lib/use-ai";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Task Planner — AI Workplace Assistant" },
      { name: "description", content: "Turn your task list into a prioritised daily or weekly schedule with AI." },
      { property: "og:title", content: "AI Task Planner" },
      { property: "og:description", content: "Prioritised daily or weekly schedules generated by AI." },
    ],
  }),
  component: PlannerPage,
});

type Block = { time: string; task: string; priority: "High" | "Medium" | "Low"; notes: string };
type Plan = { overview: string; days: { label: string; blocks: Block[] }[] };

const PRIO: Record<string, string> = {
  High: "bg-destructive/10 text-destructive",
  Medium: "bg-warning/15 text-warning-foreground",
  Low: "bg-accent text-accent-foreground",
};

function PlannerPage() {
  const [tasks, setTasks] = useState("");
  const [mode, setMode] = useState<"Daily" | "Weekly">("Daily");
  const [hours, setHours] = useState("09:00 – 17:00");
  const ai = useAI<Plan>("planner");
  const go = () => ai.run({ "Plan type": mode, "Working hours": hours, Tasks: tasks });

  const edit = (di: number, bi: number, patch: Partial<Block>) => {
    if (!ai.data) return;
    const days = ai.data.days.map((d, i) => i !== di ? d : { ...d, blocks: d.blocks.map((b, j) => j === bi ? { ...b, ...patch } : b) });
    ai.setData({ ...ai.data, days });
  };
  const remove = (di: number, bi: number) => {
    if (!ai.data) return;
    ai.setData({ ...ai.data, days: ai.data.days.map((d, i) => i !== di ? d : { ...d, blocks: d.blocks.filter((_, j) => j !== bi) }) });
  };

  return (
    <div>
      <PageHeader icon={CalendarCheck} title="AI Task Planner" desc="List your tasks and AI will prioritise them into a schedule." />
      <div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(0,3fr)]">
        <Panel title="Your input">
          <div className="space-y-4">
            <div className="field"><span>Plan type</span>
              <div className="grid grid-cols-2 gap-2">{(["Daily", "Weekly"] as const).map((m) => (
                <button key={m} onClick={() => setMode(m)} className={`rounded-lg border px-3 py-2 text-sm font-medium transition ${mode === m ? "border-primary bg-primary text-primary-foreground" : "border-border hover:bg-muted"}`}>{m}</button>))}</div>
            </div>
            <label className="field"><span>Working hours</span><input className="input" value={hours} onChange={(e) => setHours(e.target.value)} /></label>
            <label className="field"><span>Tasks *</span><textarea className="input min-h-64" value={tasks} onChange={(e) => setTasks(e.target.value)} placeholder={"One per line — add deadlines, durations or importance, e.g.\nFinish client proposal (due Friday, ~3h)"} /></label>
            <div className="flex gap-2">
              <button onClick={go} disabled={!tasks.trim() || ai.loading} className="btn-primary flex-1"><Sparkles className="h-4 w-4" />{ai.loading ? "Planning…" : `Generate ${mode.toLowerCase()} plan`}</button>
              <button onClick={() => { setTasks(""); ai.reset(); }} className="btn-outline">Clear</button>
            </div>
          </div>
        </Panel>
        <Panel title="AI schedule" badge={!!ai.data}>
          <OutputState loading={ai.loading} error={ai.error} empty={!ai.data} emptyText="Add your tasks to get an AI-prioritised schedule you can edit." onRetry={go} />
          {ai.data && !ai.loading && !ai.error && (
            <div className="space-y-6">
              <p className="rounded-xl bg-accent/60 p-4 text-sm leading-relaxed text-accent-foreground">{ai.data.overview}</p>
              {ai.data.days.map((day, di) => (
                <div key={di}>
                  <h3 className="mb-3 font-display text-base font-semibold">{day.label}</h3>
                  <ul className="space-y-2">
                    {day.blocks.map((b, bi) => (
                      <li key={bi} className="group grid gap-2 rounded-xl border border-border p-3 sm:grid-cols-[7.5rem_1fr_auto] sm:items-start">
                        <input className="input-bare text-xs font-semibold text-primary" value={b.time} onChange={(e) => edit(di, bi, { time: e.target.value })} />
                        <div className="min-w-0">
                          <input className="input-bare text-sm font-medium" value={b.task} onChange={(e) => edit(di, bi, { task: e.target.value })} />
                          <input className="input-bare text-xs text-muted-foreground" value={b.notes} onChange={(e) => edit(di, bi, { notes: e.target.value })} />
                        </div>
                        <div className="flex items-center gap-1">
                          <select value={b.priority} onChange={(e) => edit(di, bi, { priority: e.target.value as Block["priority"] })} className={`rounded-full border-0 px-2 py-0.5 text-xs font-medium ${PRIO[b.priority] ?? PRIO.Low}`}>
                            <option>High</option><option>Medium</option><option>Low</option>
                          </select>
                          <button aria-label="Remove" onClick={() => remove(di, bi)} className="rounded p-1 text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button>
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          )}
        </Panel>
      </div>
    </div>
  );
}
