import { Link, Outlet } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";
import { LayoutDashboard, Mail, NotebookPen, CalendarCheck, Menu, X, Leaf, Sparkles, ShieldAlert, Loader2, AlertCircle } from "lucide-react";

const NAV = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard },
  { to: "/email", label: "Email Generator", icon: Mail },
  { to: "/meetings", label: "Meeting Summariser", icon: NotebookPen },
  { to: "/planner", label: "Task Planner", icon: CalendarCheck },
] as const;

export function AppShell() {
  const [open, setOpen] = useState(false);
  const nav = (
    <nav className="flex flex-col gap-1">
      {NAV.map(({ to, label, icon: Icon }) => (
        <Link
          key={to}
          to={to}
          onClick={() => setOpen(false)}
          activeOptions={{ exact: true }}
          className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-sidebar-foreground/80 transition-colors hover:bg-sidebar-accent hover:text-sidebar-foreground data-[status=active]:bg-sidebar-primary data-[status=active]:text-sidebar-primary-foreground"
        >
          <Icon className="h-4 w-4" /> {label}
        </Link>
      ))}
    </nav>
  );
  const brand = (
    <div className="flex items-center gap-2.5 px-2">
      <div className="grid h-9 w-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Leaf className="h-5 w-5" /></div>
      <div className="leading-tight">
        <p className="font-display text-sm font-semibold">Workplace</p>
        <p className="text-xs text-muted-foreground">AI Productivity Assistant</p>
      </div>
    </div>
  );
  return (
    <div className="min-h-screen bg-background">
      <aside className="fixed inset-y-0 left-0 hidden w-64 flex-col gap-8 border-r border-sidebar-border bg-sidebar p-5 lg:flex">
        {brand}
        {nav}
        <div className="mt-auto rounded-xl border border-sidebar-border bg-card p-3 text-xs text-muted-foreground">
          <ShieldAlert className="mb-1.5 h-4 w-4 text-primary" />
          AI can make mistakes. Always review generated content before use.
        </div>
      </aside>
      <header className="sticky top-0 z-30 flex items-center justify-between border-b border-border bg-background/90 px-4 py-3 backdrop-blur lg:hidden">
        {brand}
        <button aria-label="Open menu" onClick={() => setOpen(true)} className="rounded-lg p-2 hover:bg-muted"><Menu className="h-5 w-5" /></button>
      </header>
      {open && (
        <div className="fixed inset-0 z-40 lg:hidden">
          <div className="absolute inset-0 bg-foreground/30" onClick={() => setOpen(false)} />
          <aside className="absolute inset-y-0 left-0 flex w-72 flex-col gap-8 bg-sidebar p-5">
            <div className="flex items-center justify-between">{brand}<button aria-label="Close menu" onClick={() => setOpen(false)} className="rounded-lg p-2 hover:bg-muted"><X className="h-5 w-5" /></button></div>
            {nav}
          </aside>
        </div>
      )}
      <main className="lg:pl-64">
        <div className="mx-auto max-w-6xl px-4 py-8 sm:px-8">
          <Outlet />
          <Disclaimer />
        </div>
      </main>
    </div>
  );
}

export function Disclaimer() {
  return (
    <p className="mt-12 flex gap-2 border-t border-border pt-6 text-xs text-muted-foreground">
      <ShieldAlert className="h-4 w-4 shrink-0 text-primary" />
      <span><strong className="text-foreground">Responsible AI:</strong> All outputs are generated by AI from your inputs. Review AI-generated content for accuracy, completeness and appropriateness before using or sharing it. Avoid entering confidential or sensitive information.</span>
    </p>
  );
}

export function PageHeader({ title, desc, icon: Icon }: { title: string; desc: string; icon: any }) {
  return (
    <div className="mb-8 flex items-start gap-4">
      <div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-accent text-accent-foreground"><Icon className="h-6 w-6" /></div>
      <div>
        <h1 className="font-display text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h1>
        <p className="mt-1 text-sm text-muted-foreground">{desc}</p>
      </div>
    </div>
  );
}

export function Panel({ title, badge, children, actions }: { title: string; badge?: boolean; children: ReactNode; actions?: ReactNode }) {
  return (
    <section className="flex flex-col rounded-2xl border border-border bg-card shadow-soft">
      <div className="flex items-center justify-between gap-2 border-b border-border px-5 py-3.5">
        <div className="flex items-center gap-2">
          <h2 className="text-sm font-semibold">{title}</h2>
          {badge && <AIBadge />}
        </div>
        {actions}
      </div>
      <div className="flex-1 p-5">{children}</div>
    </section>
  );
}

export function AIBadge() {
  return <span className="inline-flex items-center gap-1 rounded-full bg-accent px-2 py-0.5 text-[11px] font-medium text-accent-foreground"><Sparkles className="h-3 w-3" />AI-generated</span>;
}

export function OutputState({ loading, error, empty, emptyText, onRetry }: { loading: boolean; error: string | null; empty: boolean; emptyText: string; onRetry?: () => void }) {
  if (loading) return (
    <div className="flex h-full min-h-64 flex-col items-center justify-center gap-3 text-sm text-muted-foreground">
      <Loader2 className="h-6 w-6 animate-spin text-primary" /> AI is working on your request…
      <div className="mt-2 w-full max-w-sm space-y-2">{[80, 100, 65].map((w) => <div key={w} className="h-3 animate-pulse rounded bg-muted" style={{ width: `${w}%` }} />)}</div>
    </div>
  );
  if (error) return (
    <div className="flex min-h-64 flex-col items-center justify-center gap-3 text-center text-sm">
      <AlertCircle className="h-6 w-6 text-destructive" />
      <p className="text-destructive">{error}</p>
      {onRetry && <button onClick={onRetry} className="btn-outline">Try again</button>}
    </div>
  );
  if (empty) return (
    <div className="flex min-h-64 flex-col items-center justify-center gap-3 text-center text-sm text-muted-foreground">
      <div className="grid h-12 w-12 place-items-center rounded-2xl bg-muted"><Sparkles className="h-5 w-5 text-primary" /></div>
      <p className="max-w-xs">{emptyText}</p>
    </div>
  );
  return null;
}
